openapi: 3.0.0

info:
  title: Hello World
  version: '1.0'

paths:
  /hello:
    get:
      summary: It greets you!
      operationId: main.hello
      responses:
        '200':
          description: A greeting.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
