openapi: 3.0.0

info:
  title: Hello World
  version: '1.0'

paths:
  /secret:
    get:
      operationId: basic_authentication_test.get_secret
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      security:
        - basic: []

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: basic_authentication_test.basic_auth
