openapi: 3.0.0

info:
  title: Dummy
  version: '1.0'

paths:
  /people:
    get:
      operationId: nullable_query_params_test.get_people
      parameters:
        - name: name
          in: query
          schema:
            type: string
          required: false
        - name: page
          in: query
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
