openapi: 3.0.0

info:
  title: Hello World
  version: '1.0'

paths:
  /add_numbers:
    get:
      operationId: request_validation_test.add_numbers
      parameters:
        - name: a
          in: query
          schema:
            type: number
          required: true
        - name: b
          in: query
          schema:
            type: number
          required: true
      responses:
        '200':
          $ref: '#/components/responses/AddNumbersResultResponse'

  /add_numbers_json:
    post:
      operationId: request_validation_test.add_numbers_json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                b:
                  type: number
      responses:
        '200':
          $ref: '#/components/responses/AddNumbersResultResponse'

components:
  responses:
    AddNumbersResultResponse:
      description: A result.
      content:
        application/json:
          schema:
            type: object
            properties:
              sum:
                type: number
